### ISSUE TITLE
vmsAcars should be reading the altitude value properly in msfs2020

### ISSUE THREAD

**Issue by avs-code** [nabeelio/acars#40]
In the airline to which I belong, two pilots who use MSFS2020 updated to version 1.35.21.0 about a month ago. Different planes fly, but Acars' behavior is the same.

Since the last updates of the VmsAcars and in this last one (1.1.2.2448) it continues to happen, they have detected that the altitude of 10,000 feet is not read correctly, there is a variation with respect to the one indicated on the plane, which causes error in the lighting of the lights in the ascent and descent.

They must put the QHN with the value of the departure or arrival airport to obtain an actual value read by Acars that matches that of the aircraft, if the QNH standard value reported by Acars does not match that of the aircraft. They are two drivers who I think are experts in driving and they tell me that this didn't happen before.

A pilot say that when the current pressure is more far from standar more deviation in ft there are
![imagen](https://github.com/nabeelio/acars/assets/16170732/2101486b-c3f7-4399-9d22-bc93e866406c)
![imagen](https://github.com/nabeelio/acars/assets/16170732/78f75998-d1b4-490d-8ebb-7496cd1b03c3)
![imagen](https://github.com/nabeelio/acars/assets/16170732/abe5784d-e442-4b95-8141-5a0100742533)

They have tested with several aircraft, it happens when they set the altimeter to STD.
If they set the QNH for where the aircraft currently is, e.g. Aircraft 1019 hPa = Acars 36,000ft. It works correctly.

With old version 1.1.0.2372. This version reads Ground altitude and Plane altitude with the equal values, but the current version 1.1.2.2448 reads  different values and plane has the standard QNH in 10000 ft and ACARS detects different one.

On the subject, in case it helps, Disposable said this:

> 
> Can we check how msfs reads the aircraft altitude again?
> We need to use the non converted, pure altimeter reading... no matter what your altimeter setting is, acars should read the altitude as it is displayed on the primary instrument. And this value should be used for rules.

Settings:

![imagen](https://github.com/nabeelio/acars/assets/16170732/366a671c-a608-442a-b8f1-848e3cfa9c5a)

phpvms 7.0.0-dev+231219.a2b8b0 module updated at same version.

**Comment by avs-code** [comment]
STRUCT LATLONALT 	Returns the latitude, longitude and altitude of the user aircraft. 	SIMCONNECT_DATA_LATLONALT 	
https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_Misc_Variables.htm

**Comment by nabeelio** [comment]
If i revert the behavior back to the previous, would that suffice?

**Comment by avs-code** [comment]
From the test they did it with old versions, seems that it could be enough.
Anyway, for testing purposes, maybe you could create an alpha and I leave it to them to test and give me feedback about the issue.

**Comment by avs-code** [comment]
With the ACARS alpha, version 1.2.0.2449 altitude in msfs2020 is working again.
