### ISSUE TITLE
Feature Request - In sim info message on phase of flight

### ISSUE THREAD

**Issue by russellwwest** [nabeelio/acars#7]
Info Message in Simulator when phase of flight changes.

When flying, it would be nice to receive an info message inside the simulator to see the change in phase of flight (taxi, climb, descent, final approach etc)

**Comment by FatihKoz** [comment]
As the pilot in command don't you know that you started taxi or doing a final approach ? Don't get me wrong, I am just trying to get your point of view, what will be the benefit of having some text message like `Started taxi ...` ?

I understand having/requesting some penalty applied messages like `Landing Lights Rule Violated` etc, but flight state, I do not think so.
